server:
  port: 8081

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

external:
  service:
    host: https://rickandmortyapi.com
    path:
      character: /api/character/
      location: /api/location/

